services:
  - name: web
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    env:
      - key: DATABASE_URL
        fromDatabase:
          name: CaosDB
          engine: postgres
